# Basic metadata configuration for your blog.
theme = "rtc"
title = "EditionCrafter Hugo Project"
author = "Columbia University"
copyright = "Copyright © 2023, Columbia University"
languageCode = "en-US"

# Generate robots.txt for SEO
enableRobotsTXT = false

# Set to "WARNING" so that broken links don't break the build process. Default is "ERROR".
refLinksErrorLevel = "WARNING"
